svc:
  name: commenttask
  http_bind: :9000
  bind: :10000

include_mysql: /Users/zongxingquan/goland/conf/dev/mysql.yaml
include_mc: /Users/zongxingquan/goland/conf/dev/mc.yaml
include_redis: /Users/zongxingquan/goland/conf/dev/redis.yaml
include_etcd: /Users/zongxingquan/goland/conf/dev/etcd.yaml
include_kafka: /Users/zongxingquan/goland/conf/dev/kafka.yaml

log_path:
  api: /Users/zongxingquan/goland/log/commenttask/api.log
  exc: /Users/zongxingquan/goland/log/commenttask/exc.log
  debug: /Users/zongxingquan/goland/log/commenttask/debug.log
