svc:
  name: commentsvc
  http_bind: :9999
  bind: :10011

include_mysql: /Users/zongxingquan/goland/conf/dev/mysql.yaml
include_mc: /Users/zongxingquan/goland/conf/dev/mc.yaml
include_redis: /Users/zongxingquan/goland/conf/dev/redis.yaml
include_etcd: /Users/zongxingquan/goland/conf/dev/etcd.yaml
include_kafka: /Users/zongxingquan/goland/conf/dev/kafka.yaml

log_path:
  api: /Users/zongxingquan/goland/log/commentsvc/api.log
  exc: /Users/zongxingquan/goland/log/commentsvc/exc.log
  debug: /Users/zongxingquan/goland/log/commentsvc/debug.log
