svc:
  name: commentbff
  http_bind: :9990
  bind: :10001

include_etcd: /Users/zongxingquan/goland/conf/dev/etcd.yaml
include_hystrix: /Users/zongxingquan/goland/conf/dev/hystrix.yaml

log_path:
  api: /Users/zongxingquan/goland/log/comment/api.log
  exc: /Users/zongxingquan/goland/log/comment/exc.log
  debug: /Users/zongxingquan/goland/log/comment/debug.log
